server:
  port: 7827

spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

starbot:
  core:
    log:
      console: INFO
      file: INFO